[general]
language = "ko" # supported language: "ko"(Korean), "en"(English)
language_file = "config/messages.json"
method = "/ml/v1/text/generation_stream?version=2023-05-29"

[model]
supported_models = [
    "mistralai/mixtral-8x7b-instruct-v01",
    "mistralai/mistral-large",
    "meta-llama/llama-3-1-70b-instruct",
    "meta-llama/llama-3-1-8b-instruct",
    "meta-llama/llama-3-405b-instruct"
]

embedding_models = [
    "all-MiniLM-L6-v2",
    "intfloat/multilingual-e5-large"
]

cache_dir = "${TRANSFORMERS_CACHE:${HOME}/.cache/huggingface/hub}"

[url_options]
Dallas = "https://us-south.ml.cloud.ibm.com"
London = "https://eu-gb.ml.cloud.ibm.com"
Frankfurt = "https://eu-de.ml.cloud.ibm.com"
Tokyo = "https://jp-tok.ml.cloud.ibm.com"


[styles]
css = '''
<style>
    .chat-message {
        padding: 1.5rem; border-radius: 0.5rem; margin-bottom: 1rem; display: flex
    }
    .chat-message.user {
        background-color: #d3d3d3
    }
    .chat-message.bot {
        background-color: #b0c4de
    }
    .chat-message .avatar {
      width: 20%;
    }
    .chat-message .avatar img {
      max-width: 78px;
      max-height: 78px;
      border-radius: 50%;
      object-fit: cover;
    }
    .chat-message .message {
      width: 80%;
      padding: 0 1.5rem;
      color: #fff;
    }
    .stExpander {
        border: 1px solid #ddd;
        border-radius: 5px;
        margin-bottom: 10px;
    }
    .streamlit-expanderContent {
        overflow-wrap: break-word;
        word-wrap: break-word;
        hyphens: auto;
        white-space: pre-wrap !important;
    }
    .header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 0;
    }
    .header-left {
        display: flex;
        align-items: center;
    }
    .header-text {
        font-size: 2.5rem;
        margin: 0;
        margin-right: 1rem;
    }
    .stSelectbox {
        margin: 0;
    }
    .toggle-description {
        display: flex;
        align-items: center;
        margin-left: 1rem;
    }
    .description-text {
        margin: 0;
        color: rgba(250, 250, 250, 0.8);
        font-size: 0.9rem;
    }
    .stToggle {
        margin: 0 !important;
    }
    .log-container {
        border: 1px solid #ddd;
        border-radius: 5px;
        padding: 10px;
        background-color: #f9f9f9;
    }            
</style>
'''