[theme]
primaryColor = "#3B82F6"
backgroundColor = "#1E2A38"
secondaryBackgroundColor = "#2C3E50"
textColor = "#FFFFFF"
font = "sans serif"

[client]
toolbarMode = "minimal"

[logger]
level = "info"

